# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AutomatedWorkflowDocumentation
                                 A QGIS plugin
 This plugin automatically documents the whole workflow of data processing to enhance map reproducibility.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-20
        copyright            : (C) 2025 by Andreas Rademaker
        email                : andreas.rademaker@uni-muenster.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name # noqa: N802
    """Load AutomatedWorkflowDocumentation class from file AutomatedWorkflowDocumentation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .automated_workflow_documentation import AutomatedWorkflowDocumentation

    return AutomatedWorkflowDocumentation(iface)
